AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless API with API Gateway and Lambda

Resources:
  ### IAM Role for Lambda ###
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ### Lambda Function ###
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyServerlessFunction
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ message: "Hello from Serverless API!" }),
            };
          };

  ### API Gateway Rest API ###
  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyServerlessApi

  ### Root Resource Method (GET /) ###
  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !GetAtt MyApi.RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations

  ### Lambda Permission for API Gateway ###
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  ### Deployment and Stage ###
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: RootMethod
    Properties:
      RestApiId: !Ref MyApi
      StageName: dev

Outputs:
  ApiUrl:
    Description: "Invoke URL for the API"
    Value: 
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/
